name: ynab_csv
description: Ynab CSV

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  js: ^0.6.2
  meta: ^1.2.4
  jiffy: ^3.0.1
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
